map $host $upstream_svc {
  default "";
  pihole.local       pihole;
  dashdot.local      dashdot;
  prowlarr.local     prowlarr;
  bazarr.local       bazarr;
  radarr.local       radarr;
  sonarr.local       sonarr;
  lidarr.local       lidarr;
  digarr.local       digarr;
  whisparr.local     whisparr;
  muxarr.local       muxarr;
  homarr.local       homarr;
  bookshelf.local    bookshelf;
  jellyseerr.local   jellyseerr;
  janitor.local      janitor;
  deleterr.local     deleterr;
  navidrome.local    navidrome;
  notifiarr.local    notifiarr;
  byparr.local       byparr;
  autobrr.local      autobrr;
  checkrr.local      checkrr;
  portainer.local    portainer;
  jellyfin.local     jellyfin;
  recommendarr.local recommendarr;
  rutorrent.local    rutorrent;
  speedtest.local    speedtest;
  lingarr.local      lingarr;
  maintainerr.local  maintainerr;
  streamystats.local streamystats;
  meilisearch.local  meilisearch;
  metube.local       metube;
  calibre.local      calibre;
  tandoor.local      tandoor;
  flood.local        flood;
  bitmagnet.local    bitmagnet;
  sabnzbd.local      sabnzbd;
  amule.local        amule;
  amulerr.local      amulerr;
  openclaw.local     openclaw;
  syncthing.local    syncthing;
  pixelfin.local       pixelfin;
  questarr.local     questarr;
  profilarr.local    profilarr;
  cleanuparr.local   cleanuparr;
}

map $host $upstream_port {
  default 0;
  pihole.local       80;
  rutorrent.local    8080;
  tandoor.local      80;
  metube.local       8081;
  calibre.local      8083;
  lingarr.local      9876;
  maintainerr.local  6246;
  streamystats.local 3000;
  meilisearch.local  7700;
  prowlarr.local     9696;
  bazarr.local       6767;
  radarr.local       7878;
  dashdot.local      3001;
  sonarr.local       8989;
  lidarr.local       8686;
  digarr.local       3000;
  whisparr.local     6969;
  muxarr.local       8183;
  homarr.local       7575;
  bookshelf.local    8787;
  jellyseerr.local   5055;
  janitor.local      5456;
  deleterr.local     5457;
  navidrome.local    4533;
  notifiarr.local    5454;
  byparr.local       8191;
  autobrr.local      7474;
  checkrr.local      8585;
  portainer.local    9000;
  jellyfin.local     8096;
  recommendarr.local 3000;
  speedtest.local    3000;
  flood.local        3001;
  bitmagnet.local    3333;
  sabnzbd.local      8080;
  amule.local        4711;
  amulerr.local      3000;
  openclaw.local     18789;
  syncthing.local    8384;
  pixelfin.local     1280;
  questarr.local     5000;
  profilarr.local    6868;
  cleanuparr.local   11011;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
