server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;

  server_name navidrome.example.com;

  ssl_certificate     /etc/letsencrypt/live/navidrome.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/navidrome.example.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  include /etc/nginx/conf.d/30-security-headers.inc;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    set $upstream http://navidrome:4533;
    proxy_pass $upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
